apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pod-analyzer
  template:
    metadata:
      labels:
        name: pod-analyzer
    spec:
      hostPID: true
      containers:
      - name: pod-analyzer
        image: jeffgyf/consoleapi
        ports:
        - containerPort: 10080