apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-analyzer-aci
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pod-analyzer
  template:
    metadata:
      labels:
        name: pod-analyzer
    spec:
      hostPID: true
      containers:
      - name: pod-analyzer
        image: jeffgyf/consoleapi
        env:
          - name: CONSOLE_API_PRIVILEGED_MODE
            value: "true"
        securityContext:
          privileged: true
        stdin: true
        stdinOnce: true
        tty: true
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists