apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: console-api
  name: console-api-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 10080
  selector:
    name: pod-analyzer