apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server-aci
  labels:
    app: simple-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-server
  #pod template
  template:
    metadata:
      labels:
        app: simple-server
        property: console-enabled
    spec:
      shareProcessNamespace: true
      containers:
      - name: simple-server
        image: jeffgyf/simpleserver
        env:
          - name: CONTAINER_NAME
            value: "simple-server"
        ports:
        - containerPort: 80
      - name: empty-container
        image: google/pause
        env:
          - name: CONTAINER_NAME
            value: "empty-container"
      - name: sidecar
        image: alpine
        ports:
        - containerPort: 10080
        command: ["tail","-f","/dev/null"]
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists